### ISSUE TITLE
Breaks .jira.d/config.yml

### ISSUE THREAD

**Issue by rocketraman** [atlassian/gajira-transition#6]
This writes a `{}` to the last line of `.jira.d/config.yml`, which breaks any further actions that attempt to read that file, as it is invalid YAML.

**Comment by rocketraman** [comment]
The actions.yml always returns an empty object, and because of https://github.com/eemeli/yaml/issues/136 this is stringified to `{}`.

**Comment by rocketraman** [comment]
According to the upstream issue `{}` is valid YAML. However the code that parses this config borks when it sees the value without any colon. This component should just not write anything to that file.

**Comment by rudzon** [comment]
Hi, the issue should be fixed in v2.0.2 https://github.com/atlassian/gajira-transition/releases/tag/v2.0.2
